Repository obi1kenobi/trustfall, pull requests merged in 2023-10, with the labels that each got.

#478 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#477 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#483 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#482 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#435 Move to our own Type type for everything that's exposed in trustfall_core
  trustfall_core/src/frontend/mod.rs
  trustfall_core/src/interpreter/helpers/correctness.rs
  trustfall_core/src/interpreter/hints/dynamic.rs
  trustfall_core/src/interpreter/hints/vertex_info.rs
  trustfall_core/src/interpreter/mod.rs
  trustfall_core/src/ir/indexed.rs
  trustfall_core/src/ir/mod.rs
  trustfall_core/src/ir/serialization.rs
  trustfall_core/src/ir/types.rs
  trustfall_core/src/ir/types/base.rs
  trustfall_core/src/ir/types/mod.rs
  trustfall_core/src/ir/types/named_typed.rs
  trustfall_core/src/schema/adapter/mod.rs
  trustfall_core/src/schema/mod.rs
Labels: A-ir, L-rust, R-breaking-change, R-relnotes

#491 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#492 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#494 Use sccache to speed up test runs.
  .github/workflows/ci.yml
Labels: C-maintainability

#481 Allow adapters to process types that deref to their vertex type.
  demo-hytradboi/src/adapter.rs
  pytrustfall/src/shim.rs
  trustfall/examples/feeds/adapter.rs
  trustfall/examples/hackernews/adapter.rs
  trustfall/examples/hackernews/example_queries/front_page_stories_with_links.ron
  trustfall/examples/hackernews/example_queries/highly_rated_stories_by_specific_user.ron
  trustfall/examples/hackernews/example_queries/latest_links_by_high_karma_users.ron
  trustfall/examples/hackernews/example_queries/links_with_high_karma_commenters.ron
  trustfall/examples/hackernews/hackernews.graphql
  trustfall/examples/weather/adapter.rs
  trustfall/src/lib.rs
  trustfall/tests/helper_macros.rs
  trustfall_core/fuzz/fuzz_targets/adapter_batching/mod.rs
  trustfall_core/fuzz/fuzz_targets/adapter_batching/numbers_adapter.rs
  trustfall_core/src/filesystem_interpreter.rs
  trustfall_core/src/interpreter/basic_adapter.rs
  trustfall_core/src/interpreter/execution.rs
  trustfall_core/src/interpreter/helpers/mod.rs
  trustfall_core/src/interpreter/helpers/tests.rs
  trustfall_core/src/interpreter/hints/dynamic.rs
  trustfall_core/src/interpreter/hints/tests/mod.rs
  trustfall_core/src/interpreter/mod.rs
  trustfall_core/src/interpreter/replay.rs
  trustfall_core/src/interpreter/trace.rs
  trustfall_core/src/nullables_interpreter.rs
  trustfall_core/src/numbers_interpreter.rs
  trustfall_core/src/schema/adapter/mod.rs
  trustfall_stubgen/src/adapter_creator.rs
  trustfall_stubgen/src/edges_creator.rs
  trustfall_stubgen/src/properties_creator.rs
  trustfall_stubgen/src/tests.rs
  trustfall_stubgen/test_data/expected_outputs/hackernews/adapter/adapter_impl.rs
  trustfall_stubgen/test_data/expected_outputs/hackernews/adapter/edges.rs
  trustfall_stubgen/test_data/expected_outputs/hackernews/adapter/properties.rs
  trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/adapter_impl.rs
  trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/edges.rs
  trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/properties.rs
  trustfall_wasm/src/adapter.rs
  trustfall_wasm/src/shim.rs
Labels: C-enhancement, L-rust, R-breaking-change, R-relnotes

#502 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#503 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#505 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#506 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated
