Repository obi1kenobi/trustfall, pull requests merged in 2023-07, with the labels that each got.

#340 Fix dependency updater GitHub Action.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#350 Allow `TryIntoStruct` to unpack `EdgeParameters` as well.
  trustfall_core/src/ir/mod.rs
  trustfall_core/src/schema/adapter/mod.rs
  trustfall_core/src/serialization/mod.rs
Labels: A-adapter, L-rust, R-relnotes

#352 Generate more edge-handling code in `trustfall_stubgen`.
  trustfall_stubgen/src/edges_creator.rs
  trustfall_stubgen/test_data/expected_outputs/hackernews/adapter/edges.rs
Labels: A-adapter, C-enhancement, L-rust, R-relnotes

#355 Remove unnecessary lint suppressions.
  trustfall_core/src/graphql_query/query.rs
  trustfall_core/src/ir/mod.rs
Labels: C-maintainability

#358 Trigger the CI workflow manually when auto-updating dependencies.
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
Labels: C-maintainability

#360 Add `actions: write` permission to auto-updater workflow.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#361 Open dependency-updating PRs with a custom access token.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#362 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#363 Auto-update the fuzzing dependencies via an Actions workflow.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#364 Use the default GITHUB_TOKEN to auto-merge PRs.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#366 Better names for the automated workflow's jobs.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#365 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#367 Bail out if no Cargo.lock changes are needed.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#368 Print bail-out messages to stdout when updating dependencies.
  .github/workflows/dependencies.yml
Labels: C-maintainability

#370 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#369 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#373 add InvalidSchemaError::DuplicateFieldDefinition
  trustfall_core/src/schema/error.rs
  trustfall_core/src/schema/mod.rs
  trustfall_core/test_data/tests/schema_errors/interface_with_same_field_twice.graphql
  trustfall_core/test_data/tests/schema_errors/interface_with_same_field_twice.schema-error.ron
  trustfall_core/test_data/tests/schema_errors/type_with_same_field_twice.graphql
  trustfall_core/test_data/tests/schema_errors/type_with_same_field_twice.schema-error.ron
Labels: A-errors, C-enhancement

#376 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#377 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#382 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#383 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#395 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#394 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#399 Remove `chrono` from dependencies. Removes datetime value variant.
  Cargo.lock
  demo-hytradboi/Cargo.toml
  demo-hytradboi/schema.graphql
  demo-hytradboi/src/actions_parser.rs
  demo-hytradboi/src/adapter.rs
  demo-hytradboi/src/main.rs
  pytrustfall/src/shim.rs
  trustfall/examples/feeds/adapter.rs
  trustfall_core/Cargo.toml
  trustfall_core/src/interpreter/filtering.rs
  trustfall_core/src/ir/types.rs
  trustfall_core/src/ir/value.rs
  trustfall_core/src/serialization/deserializers.rs
  trustfall_wasm/src/shim.rs
Labels: A-ir, R-breaking-change, R-relnotes

#393 Run-length + custom dictionary compression for playground query URLs.
  experiments/browser_based_querying/src/TrustfallPlayground.tsx
  experiments/browser_based_querying/src/urlCompression.ts
Labels: C-enhancement, A-playground

#407 Correct escaped conversion generation; test with `cargo test --no-run`.
  trustfall_stubgen/src/edges_creator.rs
  trustfall_stubgen/src/tests.rs
  trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/edges.rs
Labels: A-adapter, C-bug, C-maintainability

#416 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#417 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated
