Repository obi1kenobi/trustfall, pull requests merged in 2023-08, with the labels that each got.

#423 add min_fold_count_limit optimization
  trustfall_core/src/interpreter/execution.rs
  trustfall_core/test_data/tests/valid_queries/fold_with_no_outputs.trace.ron
  trustfall_core/test_data/tests/valid_queries/fold_with_no_outputs_elided_braces.trace.ron
  trustfall_core/test_data/tests/valid_queries/fold_with_no_outputs_transform_and_filter_greater_than.trace.ron
  trustfall_core/test_data/tests/valid_queries/nested_fold_with_no_outputs.trace.ron
Labels: A-adapter, C-enhancement, R-relnotes

#436 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#437 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#446 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#447 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#453 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#461 Add better filter error message for string instead of array.
  trustfall_core/src/graphql_query/directives.rs
  trustfall_core/src/graphql_query/error.rs
  trustfall_core/test_data/tests/parse_errors/filter_with_value_instead_of_array.parse-error.ron
  trustfall_core/test_data/tests/parse_errors/filter_with_value_instead_of_array.ron
Labels: A-errors

#463 Add error for filter where value argument is just ["$"] or ["%"]
  trustfall_core/src/graphql_query/directives.rs
  trustfall_core/test_data/tests/parse_errors/filter_with_value_of_just_dollar_sign.parse-error.ron
  trustfall_core/test_data/tests/parse_errors/filter_with_value_of_just_dollar_sign.ron
  trustfall_core/test_data/tests/parse_errors/filter_with_value_of_just_percent_sign.parse-error.ron
  trustfall_core/test_data/tests/parse_errors/filter_with_value_of_just_percent_sign.ron
Labels: A-errors

#464 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#465 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated
