Repository obi1kenobi/trustfall, pull requests merged in 2024-01, with the labels that each got.

#532 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#533 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#535 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#536 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#539 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#538 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#540 Add information to unimplemented! messages
  trustfall_core/src/schema/mod.rs
Labels: A-schema, C-maintainability, L-rust

#543 Add reminders when stubgen is done
  trustfall_stubgen/src/main.rs
Labels: C-enhancement

#545 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated

#546 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#550 Weekly `cargo update` of primary dependencies
  Cargo.lock
Labels: R-automated

#549 Weekly `cargo update` of fuzzing dependencies
  trustfall_core/fuzz/Cargo.lock
Labels: R-automated
